<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Comportement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="etats" lowerBound="1" upperBound="-1"
        eType="#//Etat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arbitre">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comportements" upperBound="-1"
        eType="#//Comportement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effecteurs" upperBound="-1"
        eType="#//Effecteur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capteurs" upperBound="-1"
        eType="#//Capteur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effecteur" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Roue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capteur" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="produitValeur" eType="#//Valeur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapteurDistance" eSuperTypes="#//Capteur"/>
  <eClassifiers xsi:type="ecore:EClass" name="CapteurLumiere" eSuperTypes="#//Capteur"/>
  <eClassifiers xsi:type="ecore:EClass" name="CapteurInfrarouge" eSuperTypes="#//Capteur"/>
  <eClassifiers xsi:type="ecore:EClass" name="Etat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produitValeur" eType="#//Valeur"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Etat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Etat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Roue" abstract="true" eSuperTypes="#//Effecteur">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesseRotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoueAvG" eSuperTypes="#//Roue"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoueAvD" eSuperTypes="#//Roue"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoueArG" eSuperTypes="#//Roue"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoueArD" eSuperTypes="#//Roue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvancerAvD" eSuperTypes="#//ActionRoue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvancerAvG" eSuperTypes="#//ActionRoue"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionRoue" abstract="true" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roue" lowerBound="1" eType="#//Roue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvancerArG" eSuperTypes="#//ActionRoue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvancerArD" eSuperTypes="#//ActionRoue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondNegation" eSuperTypes="#//CondUnaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondEt" eSuperTypes="#//CondBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondOu" eSuperTypes="#//CondBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondBinaire" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondUnaire" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperateurBinaire" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valeurs" lowerBound="2"
        upperBound="2" eType="#//Valeur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperateurUnaire" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valeur" lowerBound="1"
        eType="#//Valeur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InferieurA" eSuperTypes="#//OperateurBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperieurA" eSuperTypes="#//OperateurBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Egal" eSuperTypes="#//OperateurBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Different" eSuperTypes="#//OperateurBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Valeur" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoolVal" eSuperTypes="#//Valeur"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatVal" eSuperTypes="#//Valeur"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntVal" eSuperTypes="#//Valeur"/>
</ecore:EPackage>
